export const CONDITIONAL_LOGIC_SELECTORS = {
  singleChoiceElement: 'add-single-choice-element',
  multipleChoicePreviewGroup: 'multiple-choice-preview-group',
  emailAddressGroup: 'email-preview-group',
  welcomeScreen: 'welcome-screen',
  thirdOption : 'option-input-2',
  deleteThirdOption: 'delete-option-button-2',
  firstOption: 'option-input-0',
  secondOption: 'option-input-1',
  optionsCard: 'choices-options-card',
  summaryButton: 'cancel-button',
  singleChoiceOptionContainer: 'single-choice-options-container',
  conditionalLogicCard: 'conditional-logic-settings-link',
  neetoMoleculesHeader: 'neeto-molecules-header',
  addNewCondition: 'conditions-new-button',
  menuList: 'nui-select-menu',
  playwrightOption: 'interested-in-playwright-?-select-option',
  questionWrapper: 'condition-question-select-input',
  verbWrapper: 'condition-verb-select-input',
  isEqualTo: 'is-equal-to-select-option',
  conditionWrapper: 'condition-value-select-input',
  secondOptionSelect: 'option-2-select-option',
  questionHeader: 'content-text-field',
  actionTypeSelectField: 'action-type-select-input',
  showOption: 'show-select-option',
  actionFieldInput: 'action-field-select-input',
  selectEmailAddress: 'email-address-select-option',
  saveChangesButton: 'save-changes-button',
  yesOption: 'yes-select-option',
  singleChoiceOption: 'form-single-choice-option',
  emailTextField: 'email-text-field',
}
